service: hashtag
org: swain

provider:
  name: aws
  runtime: nodejs10.x
  region: us-west-1
  vpc:
    securityGroupIds:
      - sg-5533302a
    subnetIds:
      - subnet-95908ece
      - subnet-b66aa8d0
  environment:
    JWT_SECRET: T97Oid2OhcGVhq2u2qsop9XIRHZlkgMlzhUA2TdUWgw
    JWT_EXPIRATION_TIME: 1h
    

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
          authorizer: authorize
          cors: true
  register:
    handler: handler.register
    events:
      - http:
          path: register
          method: post
          cors: true
  login:
    handler: handler.login
    events:
      - http:
          path: login
          method: post
          cors: true
  authorize:
    handler: handler.authorize
    
plugins:
  - serverless-offline