service: hashtag-app
org: swain

provider:
  name: aws
  runtime: nodejs10.x
  region: us-west-1
  vpc:
    securityGroupIds:
      - sg-5533302a
    subnetIds:
      - subnet-95908ece
      - subnet-b66aa8d0
  environment:
    JWT_SECRET: ThIsIsSoSeCrEtChAnGeMePlEaSe
    JWT_EXPIRATION_TIME: 1h
    

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
          authorizer: authorize
          cors: true
  user:
    handler: handler.user
    events:
      - http:
          path: user
          method: get
          authorizer: authorize
          cors: true  
  register:
    handler: handler.register
    events:
      - http:
          path: register
          method: post
          cors: true
  login:
    handler: handler.login
    events:
      - http:
          path: login
          method: post
          cors: true
  jobs:
    handler: handler.getJobs
    events:
      - http:
          path: jobs
          method: get
          authorizer: authorize
          cors: true
  jobById:
    handler: handler.getJobByID
    events:
      - http:
          path: jobs/{id}
          method: get
          authorizer: authorize
          cors: true
          request:
            parameters:
              paths:
                id: true
  Createjobs:
    handler: handler.submitJob
    events:
      - http:
          path: jobs
          method: post
          authorizer: authorize
          cors: true
  authorize:
    handler: handler.authorize

resources:
  # API Gateway Errors
  - ${file(resources/api-gateway-errors.yml)}

plugins:
  - serverless-offline
